#!/bin/bash

# MoPay Agent Icon Generation Script
# This script provides templates and instructions for creating app icons

echo "🎨 MoPay Agent Icon Generation Guide"
echo "===================================="
echo ""
echo "📱 Icon Files Needed:"
echo "  • icon.png (1024x1024) - Main app icon"
echo "  • adaptive-icon.png (1024x1024) - Android adaptive icon"
echo "  • splash-icon.png (512x512) - Splash screen icon"
echo "  • favicon.png (64x64) - Web favicon"
echo ""
echo "🎨 Design Specifications:"
echo "  • Brand Color: #007bff (MoPay Blue)"
echo "  • Secondary: #28a745 (Success Green)"
echo "  • Background: Transparent"
echo "  • Style: Modern, clean, professional"
echo ""
echo "🛠️  Recommended Tools:"
echo "  • Figma (https://figma.com)"
echo "  • Adobe Illustrator"
echo "  • Canva (https://canva.com)"
echo "  • Inkscape (free)"
echo ""
echo "📋 Quick Start:"
echo "  1. Open your design tool"
echo "  2. Create new file with specified dimensions"
echo "  3. Design circular badge with 'MP' or 'MoPay Agent'"
echo "  4. Use brand colors (#007bff primary)"
echo "  5. Export as PNG with transparent background"
echo "  6. Replace files in assets/ folder"
echo ""
echo "🔗 Resources:"
echo "  • Material Design Icons: https://materialdesignicons.com/"
echo "  • Expo Icon Guidelines: https://docs.expo.dev/guides/icons/"
echo "  • Android Adaptive Icons: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive"
echo ""
echo "✅ Current Status:"
echo "  • app.json configured ✓"
echo "  • Assets folder ready ✓"
echo "  • Placeholder icons exist ✓"
echo "  • Ready for custom icons ⏳"
echo ""
echo "🚀 Next Steps:"
echo "  1. Design icons using specifications above"
echo "  2. Export in required formats/sizes"
echo "  3. Replace files in assets/ folder"
echo "  4. Test on device: npx expo start"